# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Obviously Awesome
email: bjpcjp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Brian Piercy's personal repo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: brianpiercy
github_username:  bjpcjp

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - about.html 
  - behaviors.html
  - cmos/index.html # was cmos.html # was cpus.html
  - frontend.html
  - golang.html
  - linux.html
  - math.html
  - prodmgmt.html
  - python.html 
  - rails.html
  - ui-ux.html

# algolia search plugin API:
#algolia:
#  application_id: 0ST64V6V0J
#  index_name: jekyll
#  search_only_api_key: e850d8fbd248c7d7df4a35544f104d32
#  #
#  extensions_to_index:
#    - html
#    - md 
#    - txt 
#    #
#  nodes_to_index: 'p,div.card,div.textcard,blockquote'
  
# pagination:
paginate: 20
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus:
  shortname: brianpiercy