# Welcome to Jekyll!
#
# Site settings

title: Obviously Awesome
email: bjpcjp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Brian Piercy's personal repo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bjpcjp.github.io"
twitter_username: brianpiercy
github_username:  bjpcjp

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# excerpt visibility
show_excerpts: true 

# navigation links
header_pages:
  - about.html 
  - behaviors.html
  - cmos.html # was cmos/index.html # was cmos.html # was cpus.html
  - golang.html
  - linux.html
  - math.html
  - prodmgmt.html
  - python.html 
  - rails.html
  - ui-ux.html
  - webdev.html
  #- ril_export/ril_export-2020-02-15-unread.html 
  #- ril_export/ril_export-2020-02-15-archive.html 
  #- ril_export/ril_export-2020-02-19.html

# collections
#
#
#


# algolia search plugin API:
#algolia:
#  application_id: 0ST64V6V0J
#  index_name: jekyll
#  search_only_api_key: e850d8fbd248c7d7df4a35544f104d32
#  #
#  extensions_to_index:
#    - html
#    - md 
#    - txt 
#    #
#  nodes_to_index: 'p,div.card,div.textcard,blockquote'
  
# pagination:
paginate: 20
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

disqus:
  shortname: brianpiercy